name: 'Elixir Config Checker'
description: 'Github action for checking the elixir runtime config against kubernetes env'
inputs:
  webhook:
    description: 'Slack Webhook URL'
    required: true
  elixir-config:
    description: 'Path to Elixir Config'
    required: true
  envsource:
    description: 'Path to env var source'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Inject variables
      run: | 
        echo "INPUT_WEBHOOK=${{ inputs.webhook }}" >> $GITHUB_ENV
        echo "INPUT_ENVSOURCE=${{ inputs.envsource }}" > $GITHUB_ENV
      shell: bash
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run Checker
      run: python ${{ github.action_path }}//app.py
      shell: bash

